### ISSUE TITLE
Shaderc dependency potentially causes docs.rs build to fail.

### ISSUE THREAD

**Issue by mobile-bungalow** [hasenbanck/egui_wgpu_backend#1]
Great work on implementing the back end!

 I noticed your docs were failing to build because of a timeout. I assume this is due to the high compile time of shaderc-sys and wgpu. The shaderc-sys dependency could be removed if you precompiled your shaders like in the [wgpu examples](https://github.com/gfx-rs/wgpu-rs/tree/master/examples/hello-triangle).

**Comment by hasenbanck** [comment]
PR's are welcome. But the build process should be automated if possible.

**Comment by mobile-bungalow** [comment]
I'm not certain that the build process can be automated in a well principled way. A build.rs that calls `glslLangValidator` would fail on some machines. The closest I can come to the desired behavior is shipping a Makefile which the developer can call as they change the glsl. If this is too hacky we should close this issue in favor of using the current shader compilation macros.

**Comment by hasenbanck** [comment]
Lets stick with the current implementation then for now. Users who use wgpu have shaderc installed anyhow.

The proper solution in the long run would either to use [naga](https://github.com/gfx-rs/naga) or [rust-gpu](https://github.com/EmbarkStudios/rust-gpu), but naga isn't ready yet and rust-gpu still needs the nightly compiler to work at all (and the external spirv toolset).

**Comment by hasenbanck** [comment]
Btw, the docs seem to build right now properly on docs.rs.
