### ISSUE TITLE
Allow replacing wgpu::Texture for a given egui::TextureId

### ISSUE THREAD

**Issue by zachreizner** [hasenbanck/egui_wgpu_backend#30]
I have a use case where I'm embedding a wgpu rendered texture target inside a window as an `egui::Image`. The window is dynamically sized requiring that the underlying wgpu render texture target be resized. In wgpu, textures can not be resized so I make a new `wgpu::Texture` on resize. This invalidates the `egui::TextureId` made with `egui_wgpu_backend::egui_texture_from_wgpu_texture`. I could create a new `egui::TextureId` using that function every time a new `wgpu::Texture` is made as a render target, but this has two downsides.

- The `egui::TextureId` and underlying `RenderPass::user_textures` `Vec` would grow monotonically. Because resizes can happen thousands of times, many times per second, this represents a waste of memory, even after using `free` to forget the old textures.
- Because of how `egui` does layout, the size of the `egui::Image` widget is only known after it is placed, which requires knowing the `egui::TextureId` ahead of time. If a resize is needed after the `TextureId` is already committed, that will mean there is a single frame delay between a resize happening and having the properly sized texture. An extra repaint will also be needed.

I could solve this issue by replacing the backing `wgpu::Texture` for an already allocated `TextureId`. I have prototyped this using a method on `RenderPass` like this:

```rust
/// Registers a `wgpu::Texture` with an existing `egui::TextureId`.
///
/// This enables applications to reuse `TextureId`s
pub fn update_egui_texture_from_wgpu_texture(
    &mut self,
    device: &wgpu::Device,
    texture: &wgpu::Texture,
    texture_filter: wgpu::FilterMode,
    id: egui::TextureId,
) { ... }
```

The implementation was a mostly trivial copy of `egui_texture_from_wgpu_texture`.

**Comment by hasenbanck** [comment]
PR are welcome. As long as you don't change existing functionality for only your specific usecase, adding functionality is welcome.

**Comment by zachreizner** [comment]
Excellent. I'm happy to contribute.
