### ISSUE TITLE
Allow TextureId creation/updates with custom Sampler options

### ISSUE THREAD

**Issue by Kneelawk** [hasenbanck/egui_wgpu_backend#42]
# Issue
I am currently working on a specialized image viewer program using Egui and WGPU. My image viewer needs to be able to properly blend pixels when zooming out of an image (using `FilterMode::Linear` for MIN filter) but allow the image to become pixelated when zooming in (using `FilterMode::Nearest` for MAG filter) for better per-pixel controls.

Currently the `RenderPass` API only supports supplying WGPU textures with a single `FilterMode` for both MIN and MAG filters. It would be useful to have WGPU texture methods that allow users to specify both MIN and MAG `FilterMode`s individually.

# Solution
One way to solve this problem would be to add separate WGPU texture methods accepting entire `BindGroup`s instead of just `Texture`s and `FilterMode`s. These methods would specify the required bind group and sampler parameters but would leave the rest up to the API user. In order to allow creation of custom `BindGroup`s, a method for exposing a reference to the `RenderPass`'s `BindGroupLayout` should be added.

# Discussion Points
* Are there any maintainability or API concerns with allowing the API user to supply their own `BindGroup`s?
* Are there any maintainability or API concerns with allowing the API user access to the `RenderPass`'s internal `BindGroupLayout`?
* What requirements are there for `BindGroup`s being submitted? From what I can tell:
   - Bound `TextureView`s should refer to textures with format `TextureFormat::Rgba8UnormSrgb` and usage `TextureUsage::SAMPLED`.
   - Bound `TextureView`s should have the dimension `D2`.
   - Bound `Sampler`s should not have the compare function.
   - The `BindGroup` should consist of 2 entries. The first entry should have the binding `0` and the texture view as its resource. The second entry should have the binding `1` and the sampler as its resource.

# Pull Request
My plan is to submit a pull request to solve this issue by adding new API methods for exposing the `RenderPass`'s `BindGroupLayout` and creating and updating texture ids from `BindGroup`s.

**Comment by hasenbanck** [comment]
I have a feeling that you took the most complicated route to fix your problem.

You essentially just want to be able to configure the MAG/MIN filters seperately.

Why not just extend the API signature of `update_egui_texture_from_wgpu_texture()` to both expose the min_texture_filter and max_texture filter? We could also change the signature to expose the "SamplerDescriptor" instead!

Doing this by exposing the `BindGroup` feels like the wrong approach, especially if you consider that the requirements required for the `egui_texture_from_wgpu_bind_group()` function makes it really hard to use and very specific.

**Comment by Kneelawk** [comment]
Makes sense. The main reason I went with bind groups was because I wanted to provide a way for people with other use cases besides my individual MIN/MAG filter case to supply their arguments to `Sampler` and `TextureView` creation. This could be handled by exposing `SampleDescriptor` as you suggested.

Upon further investigation, it appears that `TextureViewDescriptor::default()` satisfies the vast majority of `TextureView` use cases. So exposing `TextureViewDescriptor` would likely not be necessary.

I will look into implementing these changes as soon as possible.

**Comment by hasenbanck** [comment]
Yeah, exposing `TextureViewDescriptor` is most likely not needed for the vast majority of use cases. So exposing just the `SamplerDescriptor` is most likely enough.

**Comment by hasenbanck** [comment]
The function right now takes a texture and all other texture related
functions do so too. I would not change the Texture to a TextureView
without a pressing need.

**Comment by Kneelawk** [comment]
Sounds good.

**Comment by Kneelawk** [comment]
I have submitted another PR that takes the approach you suggested: #45.
