### ISSUE TITLE
`no memory left` crash

### ISSUE THREAD

**Issue by Lucky4Luuk** [hasenbanck/egui_wgpu_backend#44]
When allocating a texture and freeing it immediately like the code below, after a few hundred frames rendered, it crashes with a `no memory left` error.

Code:
```rust
let image_tex_id = tex_allocator.alloc_srgba_premultiplied(pixels_size, &pixels);
ui.image(image_tex_id, size);
tex_allocator.free(image_tex_id);
```

Error:
```
 ERROR wgpu_hal::dx12::descriptor > Unable to allocate descriptors: RangeAllocationError { fragmented_free_length: 0 }
 ERROR wgpu::backend::direct      > Handling wgpu errors as fatal by default
thread 'main' panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_bind_group
      note: label = `user_texture2046_texture_bind_group`
    not enough memory left

', C:\Users\luukv\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.11.0\src\backend\direct.rs:2195:5
```

Seems like there is an issue freeing textures like this? My texture changes every frame, and it is not a WGPU texture so I figured this would be a quick solution, and I don't see a problem with doing this either.

**Comment by hasenbanck** [comment]
`alloc_srgba_premultiplied()` queues the texture for upload. You then try to free it before it's actualy uploaded! `free()` will only free textures that have finished uploading! So in your example `tex_allocator.free(image_tex_id);` is a NOP.

I would either free the texture at the start of the next frame, or better just update the old texture.

**Comment by Lucky4Luuk** [comment]
Aaah, that makes a lot of sense. I read the docs but I don't remember seeing that. Thanks for the info!
