### ISSUE TITLE
Allow for In-Shader SRGB conversion

### ISSUE THREAD

**Issue by cwfitzgerald** [hasenbanck/egui_wgpu_backend#46]
If rendering egui to the surface texture, there is a decent chance it will _not_ be a srgb texture (Chrome/WebGPU is Bgra8Unorm right now, and GL likes to be SRGB-less due to how silly GL is). It would be nice to somehow be able to instantiate a egui backend that does the srgb conversion in the shader.  This is how we ended up doing it in the wgpu imgui backend.

**Comment by hasenbanck** [comment]
There's already a crate feature "web" that uses a special shader for the web to handle this (or at least it was supposed to do so).
Maybe it's better to select the appropriate shader when creating the Renderpass based on a given configuration?

**Comment by cwfitzgerald** [comment]
Ah I didn't notice that. Yeah there are a couple situations where having it as a parameter to the RP would be helpful, plus the Web is _supposed_ to support srgb at some point,but browser rollout of that might be staggered.

**Comment by hasenbanck** [comment]
A PR to change the feature "web" into a parameter is welcome. I don't use egui anymore, so I couldn't test the change.
