### ISSUE TITLE
Allow Re-use of External Renderpass 

### ISSUE THREAD

**Issue by cwfitzgerald** [hasenbanck/egui_wgpu_backend#47]
Due to how mobile gpus work, it is advantageous to use as few renderpasses as possible. It should be near-trivial to convert execute's interface to take an external renderpass so that users can share renderpasses between egui and other rendering operations.

We could also make there be two executes, one on a texture with an internal renderpass, and one with a external renderpass if you want to keep the ease-of-use option.

If you're down with this, I can pr both this and #46 probably tomorrow.

**Comment by hasenbanck** [comment]
As discusses on Discord, this change is reasonable and good.
