### ISSUE TITLE
Expose a way to register textures with a `TextureView`

### ISSUE THREAD

**Issue by setzer22** [hasenbanck/egui_wgpu_backend#53]
Sometimes, you don't have a `wgpu::Texture`, just a `wgpu::TextureView`. Methods like `RenderPass::egui_texture_from_wgpu_texture` are not useful in that case, but looking at the implementation, the only reason those methods take a `Texture` is to create a `TextureView`.

I think making the methods take `TextureView` just relaxes the requirements of the API (everywhere you have a `Texture`, you can trivially create the view). But this has the unfortunate side effect of breaking the public API.

I'd be happy to send in a PR if you let me know what's your preferred fix for this :smile:

**Comment by hasenbanck** [comment]
Closed by #54
