### ISSUE TITLE
Support WASM (WebGL backend) by increasing the UniformBuffer size to 16

### ISSUE THREAD

**Issue by Oberdiah** [hasenbanck/egui_wgpu_backend#58]
Currently egui_wgpu breaks when running on Firefox or Chrome using the wgpu WebGL backend, because it has a minimum buffer size restriction of 16.

Presumably it could be fixed by padding UniformBuffer with some extra zeroes, but I've not looked into it much beyond that.

**Comment by hasenbanck** [comment]
Should be fixed on master.
