### ISSUE TITLE
Update to the latest wgpu and egui

### ISSUE THREAD

**Issue by autriz** [hasenbanck/egui_wgpu_backend#79]

**Comment by adamkirkland** [comment]
I have the same issue with version clashes - try forking the project and specifying it as a local dependency in your cargo.toml file, so you can make the upgrade yourself.

**Comment by David-OConnor** [comment]
+1. We may need to fork this lib because it's been since jan, and this is still a thing.

**Comment by hasenbanck** [comment]
The library was updated three times since January. PRs are welcome if you need an update for this project.
